### ISSUE TITLE
Using 1.18 API

### ISSUE THREAD

**Issue by YodaZen** [UnderscoreTud/diskuise#6]
Hey, I would like to use the addon on my server, but aren't able because of the use of 1.18 API.
My server version is 1.17.1

I saw on your changelog that you said it supports 1.16+, but it doesn't :)

[00:43:51 ERROR]: Could not load 'plugins/Diskuise.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.18

**Comment by UnderscoreTud** [comment]
Oh, right. My bad 😅
