### ISSUE TITLE
I have a question :)

### ISSUE THREAD

**Issue by YodaZen** [UnderscoreTud/diskuise#9]
[13:39:58 INFO]:     Can't understand this expression: 'disguise type player with username "%{_Disguise}%"'

I am getting an error here, why is that?

if arg-1 = "disguise":
	if arg-2 is a offline player:
		set {Streamermode::skin::%uuid of player%} to arg-2
		Disguise(player, arg-2)

function Disguise(p: player, Disguise: offline player):
	set {_u} to uuid of {_p}
	set {Disguise::%{_u}%} to disguise type player with username "%{_Disguise}%"
	set {_p}'s disguise to {Disguise::%{_u}%}
	message "{@p}Du er forklædt som &6%{_Disguise}%" to {_p}
	stop

**Comment by UnderscoreTud** [comment]
The syntax for a player disguise is `disguise %entity% as "_tud" player disguise`

**Comment by YodaZen** [comment]
okay, thanks im trying that then :)
